name: CI

on:
  push:
    branches:
      - main
      - website

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: curl -O https://mirror.nodesdirect.com/apache/jena/binaries/apache-jena-4.1.0.tar.gz
      - run: tar xzf apache-jena-4.1.0.tar.gz
      - run: while read line; do ./apache-jena-4.1.0/bin/riot --validate "$line"; done < ./.github/ontologies.txt
  website:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: python -m pip install -r https://raw.githubusercontent.com/amoeba/pyLODE/master/requirements.txt
      - run: python -m pip install git+https://github.com/amoeba/pylode.git
      - run: python -m pip install jinja2
      # - run: python website/build.py
      # - name: ghpages
      #   uses: JamesIves/github-pages-deploy-action@4.1.3
      #   with:
      #     branch: gh-pages
      #     folder: website
