name: Build website

on:
  push:
    branches:
      - main
      - website

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install pylode
      - run: python website/build.py
