name: Build website

on:
  push:
    branches:
      - main
      - website

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python -m pip install pylode
      - run: python -m pip install jinja2
      - run: python website/build.py
      - name: ghpages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: website
